### ISSUE TITLE
Re-train the model with new data: 3 view aggregation

### ISSUE THREAD

**Issue by rockNroll87q** [abhi4ssj/quickNAT_pytorch#13]
Dear authors,

First of all, great work and thanks for the code!
I'm trying to re-train the model with my data and it seems to run.

I only have a question. It seems possible to select the orientation (COR, AXI, SAG), but how I create a model that aggregate all of these 3?

Thanks!

**Comment by abhi4ssj** [comment]
Hi,

Details for training and deploying with View Aggregation is added in the recent commits. I omitted the SAG axis and only used AXI and COR for now to optimize between performance and deployment time.

Best
Abhijit
