### ISSUE TITLE
I can't find pretrained model

### ISSUE THREAD

**Issue by noma000** [abhi4ssj/quickNAT_pytorch#14]
Thank you for your work.

I want to run a segmentation using your code

But i could not find a model that was pretrained model by pytorch

How can i find the pretrainined model files 

Thank you

**Comment by AlimBhatia** [comment]
Were you able to find a pre-trained model? Is this solved?

**Comment by adhering** [comment]
Like noma000, I can't find the pre-trained model.
In the settings, you set
eval_model_path = "saved_models/quicknat_finetuned_1.pth.tar".
However, there is no folder saved_models or a quicknat_finetuned_1.pth.tar file somewhere. 

Could you please provide those? Thanks!

And would it be possible to provide also a sample data to get it run before adapting it to own data? That would be great!

**Comment by sairamgeethanath** [comment]
@abhi4ssj I have the same issue. I cannot find a pretrained model. Any updates?

**Comment by abhi4ssj** [comment]
Hi everyone,

Sorry for the delay. I was super-busy for last couple of months. New updates are pushed recently. I have the trained models for fine-tuned and IXI FS net with detailed explanation of deployment.

Best
Abhijit
