### ISSUE TITLE
Fixed - Installing Requirements Error: squeeze_and_excite

### ISSUE THREAD

**Issue by AndreiRoibu** [abhi4ssj/quickNAT_pytorch#18]
Just to let other users know, when running the requirements.txt installation in a venv, our team encountered an error:

> raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/git/

We found that the fix for this issue was to manually run the command bellow. When testing the pip install requirements.txt again, the issue appeared to be solved.

> pip install https://github.com/abhi4ssj/squeeze_and_excitation/releases/download/v1.0/squeeze_and_excitation-1.0-py2.py3-none-any.whl

**Comment by abhi4ssj** [comment]
Hi Andrei,

Thanks for pointing this out. I saw that I missed the `squeeze and excite' module from the requirements.txt file. I made the changes.

Best
Abhijit

**Comment by abhi4ssj** [comment]
Closed due to inactivity and issue resolved.
