### ISSUE TITLE
'phase' not used in cm_per_epoch()

### ISSUE THREAD

**Issue by iagooteroc** [abhi4ssj/quickNAT_pytorch#24]
The "phase" parameter in the cm_per_epoch() function is not passed to the dice_confusion_matrix() function. Instead, the "train" mode is used even in the validation phase.

https://github.com/ai-med/quickNAT_pytorch/blob/920d85ea5cfb621a5f574796677778df58e31d55/utils/log_utils.py#L62

**Comment by abhi4ssj** [comment]
Good catch! I updated the line. Thanks.
